"""
Test finale del collegamento ordini-prodotti
Generated by Copilot
"""

import sys
import os

# Aggiungi il percorso del backend
current_dir = os.path.dirname(os.path.abspath(__file__))
backend_path = os.path.join(current_dir, 'backend')
sys.path.insert(0, backend_path)

from crud import MagazzinoTeleCRUD

def test_final_connection():
    """Test finale del collegamento tra ordini e prodotti"""
    crud = MagazzinoTeleCRUD()
    
    try:
        if crud.connect():
            print("✅ Connessione database riuscita")
            
            cursor = crud.connection.cursor()
            
            # Query per verificare l'ordine completo
            query = """
            SELECT o.`codice ordine`, o.data, c.descrizione,
                   p.`Nome Modello`, p.`Nome Colore`, op.quantita
            FROM ordini o
            LEFT JOIN customers c ON o.`codice cliente` = c.codice
            JOIN ordiniprodotti op ON o.`codice ordine` = op.`codice ordine`
            JOIN prodotti_completi p ON op.`codice prodotto` = p.`Codice Prodotto`
            WHERE o.`codice ordine` = %s
            """
            
            cursor.execute(query, (1,))
            result = cursor.fetchone()
            
            if result:
                print("✅ Ordine completo trovato:")
                print(f"  - Ordine: {result[0]}")
                print(f"  - Data: {result[1]}")
                print(f"  - Cliente: {result[2] or 'N/A'}")
                print(f"  - Prodotto: {result[3]} - {result[4]}")
                print(f"  - Quantità: {result[5]}")
                
                print("\n🎉 SUCCESS: Database correttamente collegato!")
                print("✅ Foreign Key create")
                print("✅ Ordine con prodotto funzionante")
                print("✅ JOIN tra tabelle operativo")
                
            else:
                print("❌ Nessun ordine trovato")
            
            cursor.close()
            crud.disconnect()
            
        else:
            print("❌ Errore connessione database")
            
    except Exception as e:
        print(f"❌ Errore: {e}")

if __name__ == "__main__":
    test_final_connection()
