@echo off
REM Generated by Copilot
REM Script di avvio per Magazzino Tele su Windows

echo ================================================
echo           MAGAZZINO TELE - AVVIO
echo ================================================
echo.

REM Controlla se Python è installato
python --version >nul 2>&1
if errorlevel 1 (
    echo ❌ Python non trovato!
    echo    Installa Python 3.8+ da https://python.org
    echo.
    pause
    exit /b 1
)

echo ✅ Python trovato
echo.

REM Vai nella directory dello script
cd /d "%~dp0"

REM Controlla se le dipendenze sono installate
echo 🔄 Controllo dipendenze...
python -c "import mysql.connector" >nul 2>&1
if errorlevel 1 (
    echo ❌ Dipendenze mancanti!
    echo.
    set /p choice="Installare automaticamente? (s/n): "
    if /i "%choice%"=="s" (
        echo.
        echo 📦 Installazione dipendenze...
        python install_dependencies.py
        echo.
    ) else (
        echo    Esegui manualmente: python install_dependencies.py
        pause
        exit /b 1
    )
)

echo ✅ Dipendenze OK
echo.

REM Avvia l'applicazione
echo 🚀 Avvio applicazione...
echo.
python interfaccia\main_modular.py

REM Se c'è un errore, mostra il messaggio
if errorlevel 1 (
    echo.
    echo ❌ Errore durante l'avvio!
    echo    Controlla la configurazione del database
    echo.
)

pause
