"""
Package pages per Magazzino Tele
Moduli delle pagine principali dell'applicazione
Generated by Copilot
"""

from .welcome import WelcomePage
from .ordini import CreaOrdinePage

__all__ = ['WelcomePage', 'CreaOrdinePage']
