"""
Pagina di benvenuto per Magazzino Tele
Sistema di gestione inventario e ordini
Generated by Copilot
"""

import tkinter as tk
from tkinter import ttk
from typing import Callable


class WelcomePage:
    """Pagina di benvenuto dell'applicazione"""
    
    def __init__(self, root: tk.Tk, on_continue: Callable[[], None]):
        self.root = root
        self.on_continue = on_continue
        self.setup_ui()
    
    def setup_ui(self) -> None:
        """Configura l'interfaccia della pagina di benvenuto"""
        # Frame principale con sfondo colorato
        main_frame = ttk.Frame(self.root, padding="50")
        main_frame.pack(fill=tk.BOTH, expand=True)
        
        # Logo/Icona (placeholder)
        icon_frame = ttk.Frame(main_frame)
        icon_frame.pack(pady=(0, 30))
        
        icon_label = ttk.Label(
            icon_frame,
            text="🏭",
            font=("Arial", 48)
        )
        icon_label.pack()
        
        # Titolo principale
        title_label = ttk.Label(
            main_frame,
            text="Magazzino Tele",
            font=("Arial", 28, "bold"),
            foreground="#2c3e50"
        )
        title_label.pack(pady=(0, 10))
        
        # Sottotitolo
        subtitle_label = ttk.Label(
            main_frame,
            text="Sistema di Gestione Inventario e Ordini",
            font=("Arial", 16),
            foreground="#7f8c8d"
        )
        subtitle_label.pack(pady=(0, 50))
        
        # Informazioni sistema
        info_frame = ttk.LabelFrame(main_frame, text="Informazioni Sistema", padding="20")
        info_frame.pack(pady=(0, 30), fill=tk.X)
        
        features = [
            "✓ Gestione completa ordini e clienti",
            "✓ Inventario prodotti in tempo reale",
            "✓ Ricerca avanzata con autocomplete",
            "✓ Database MySQL integrato"
        ]
        
        for feature in features:
            ttk.Label(info_frame, text=feature, font=("Arial", 11)).pack(anchor=tk.W, pady=2)
        
        # Bottone per iniziare
        button_frame = ttk.Frame(main_frame)
        button_frame.pack(pady=20)
        
        start_button = ttk.Button(
            button_frame,
            text="🚀 Inizia Subito",
            command=self.on_continue,
            style="Accent.TButton"
        )
        start_button.pack(pady=10)
        start_button.focus()
        
        # Footer
        footer_label = ttk.Label(
            main_frame,
            text="Generated by Copilot - Sistema Magazzino Tele v1.0",
            font=("Arial", 9),
            foreground="#95a5a6"
        )
        footer_label.pack(side=tk.BOTTOM, pady=(30, 0))
        
        # Bind Invio per avvio rapido
        self.root.bind('<Return>', lambda e: self.on_continue())
    
    def show(self):
        """Mostra la pagina di benvenuto"""
        self.setup_ui()
    
    def destroy(self):
        """Rimuove tutti i widget della pagina"""
        for widget in self.root.winfo_children():
            widget.destroy()
